In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR

In [2]:
df = pd.read_csv("/content/drive/MyDrive/#2-M.Sc Computer Science [SXC]/1st Year/Books and notes/Sem 4/Machine Learning/SM+SS/27-03-23/employees.csv")
df.head()

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945   
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170   
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340   
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389   

  Senior Management             Team  
0              True        Marketing  
1              True              NaN  
2             False          Finance  
3              True          Finance  
4              True  Client Services

In [3]:
df = df.drop(columns=["First Name", "Last Login Time"], axis=1)

In [4]:
df.head()

Gender Start Date  Salary  Bonus % Senior Management             Team
0    Male   8/6/1993   97308    6.945              True        Marketing
1    Male  3/31/1996   61933    4.170              True              NaN
2  Female  4/23/1993  130590   11.858             False          Finance
3    Male   3/4/2005  138705    9.340              True          Finance
4    Male  1/24/1998  101004    1.389              True  Client Services

In [5]:
df['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [8]:
df['Gender'] = df['Gender'].fillna("Other")

In [9]:
df['Gender'].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [10]:
gender_dict = {
    "Male": 0,
    "Female": 1,
    "Other": 2
}
df['Gender'] = df['Gender'].apply(lambda el: gender_dict[el])

In [11]:
df['Gender'].unique()

array([0, 1, 2])

In [12]:
df['Senior Management'] = df['Senior Management'].apply(lambda el: 1 if el else 0)

In [13]:
df.head()

Gender Start Date  Salary  Bonus %  Senior Management             Team
0       0   8/6/1993   97308    6.945                  1        Marketing
1       0  3/31/1996   61933    4.170                  1              NaN
2       1  4/23/1993  130590   11.858                  0          Finance
3       0   3/4/2005  138705    9.340                  1          Finance
4       0  1/24/1998  101004    1.389                  1  Client Services

In [14]:
df['Team'] = df['Team'].fillna("Other")

In [15]:
team_dict = {}
for i, el in enumerate(df['Team'].unique()):
  team_dict[el] = i

In [17]:
team_dict['Other'] = 0
team_dict['Marketing'] = 1

In [18]:
team_dict

{'Marketing': 1,
 'Other': 0,
 'Finance': 2,
 'Client Services': 3,
 'Legal': 4,
 'Product': 5,
 'Engineering': 6,
 'Business Development': 7,
 'Human Resources': 8,
 'Sales': 9,
 'Distribution': 10}

In [19]:
df['Team'] = df['Team'].apply(lambda el: team_dict[el])

In [20]:
df.head()

Gender Start Date  Salary  Bonus %  Senior Management  Team
0       0   8/6/1993   97308    6.945                  1     1
1       0  3/31/1996   61933    4.170                  1     0
2       1  4/23/1993  130590   11.858                  0     2
3       0   3/4/2005  138705    9.340                  1     2
4       0  1/24/1998  101004    1.389                  1     3

In [21]:
df['Year'] = df['Start Date'].apply(lambda el: el.split("/")[-1])

In [23]:
df = df.drop(columns=['Start Date'], axis=1)

In [24]:
df.head()

Gender  Salary  Bonus %  Senior Management  Team  Year
0       0   97308    6.945                  1     1  1993
1       0   61933    4.170                  1     0  1996
2       1  130590   11.858                  0     2  1993
3       0  138705    9.340                  1     2  2005
4       0  101004    1.389                  1     3  1998

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             1000 non-null   int64  
 1   Salary             1000 non-null   int64  
 2   Bonus %            1000 non-null   float64
 3   Senior Management  1000 non-null   int64  
 4   Team               1000 non-null   int64  
 5   Year               1000 non-null   object 
dtypes: float64(1), int64(4), object(1)
memory usage: 47.0+ KB


In [26]:
df['Year'] = df['Year'].astype("int64")

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             1000 non-null   int64  
 1   Salary             1000 non-null   int64  
 2   Bonus %            1000 non-null   float64
 3   Senior Management  1000 non-null   int64  
 4   Team               1000 non-null   int64  
 5   Year               1000 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 47.0 KB


In [28]:
from sklearn.model_selection import train_test_split

In [31]:
X = df.drop(columns=['Salary'], axis=1)
Y = df['Salary']
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=43)

In [32]:
model = LinearRegression()

In [33]:
model.fit(x_train, y_train)

LinearRegression()

In [36]:
new_data = [[1, 11.76, 0, 2, 1998], [0, 5.88, 1, 1, 1992], [1, 2.00, 0, 0, 2023]]
pred = model.predict(new_data)
pred

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([91243.85495321, 92157.80845877, 96040.0889639 ])

In [42]:
model2 = SVR(kernel = 'linear')

In [43]:
model2.fit(x_train, y_train)

SVR(kernel='linear')

In [44]:
model2.score(x_test, y_test)

0.0033100018805916065

In [45]:
new_data = [[1, 11.76, 0, 2, 1998], [0, 5.88, 1, 1, 1992], [1, 2.00, 0, 0, 2023]]
pred = model2.predict(new_data)
pred

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([89566.51734724, 89793.19477816, 93037.38875316])